[env]
MSF_PASSWORD="MYSPORTSFEEDS"
MSF_API_KEY="163db9fd-bdbe-4bd4-a4b8-15324f"
MSF_GAMES_URL="https://api.mysportsfeeds.com/v2.1/pull/nhl/2023-regular/games.json?date="
MSF_GAME_BY_DATE_ENDPOINT="https://api.mysportsfeeds.com/v2.1/pull/nhl/2023-regular/games.json?date="
YAHOO_CLIENT_ID="dj0yJmk9QWRiRkUyN3dhR08zJmQ9WVdrOU0xbFBjVmd4ZDB3bWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTg0"
YAHOO_CLIENT_SECRET="48d59ea655377f654246ffb8d3bfd659ddaf6728"
YAHOO_AUTH_ENDPOINT="https://api.login.yahoo.com/oauth2/request_auth"
YAHOO_TOKEN_URL="https://api.login.yahoo.com/oauth2/get_token"
YAHOO_AUTH_CODE="antwmh5"


